### ISSUE TITLE
Capitalization issue prevents successful build on platforms with case-sensitive filenames.

### ISSUE THREAD

**Issue by deverac** [dgis/emu48android#11]
In ./app/src/main/cpp/core, the capitalization of the filename and the reference to the filename don't match for 'Ops.h' and 'Opcodes.h'. e.g. Files reference 'opcodes.h', but the file is named 'Opcodes.h' (note the capital 'O'). This is probably not an issue on platforms where filenames are case-insensitive, but prevents a successful build on platforms where filenames are case-sensitive.

**Comment by dgis** [comment]
It is better for now but the issue is actually in the original core files from emu48.
