### ISSUE TITLE
Save config with state file

### ISSUE THREAD

**Issue by SammysHP** [dgis/emu48android#12]
Today I noticed that the configured port 2 bin file is shared between all state files. I have different state files for different calculator models (who would have guessed!) and for different purposes (private, work, testing). It would be great if you could select a different RAM card file for each state file.

In addition most other settings like layout, zoom etc. are also related to a specific state file.

**Comment by dgis** [comment]
Almost all the settings are now saved at the end of the state file (This commit and the previous fix #12).
