### ISSUE TITLE
Landscape use

### ISSUE THREAD

**Issue by gbraad** [dgis/emu48android#18]
Rotation will currenrly strech/distort the interface by not maintaining the aspect ratio. Is it possible to switch between a portrait and landscape definition?

**Comment by gbraad** [comment]
![Screenshot_20211121-094414_Emu48.jpg](https://user-images.githubusercontent.com/1894/142747409-da061803-9eff-4421-bd50-96f9e1549240.jpg)![Screenshot_20211121-094431_Emu48.jpg](https://user-images.githubusercontent.com/1894/142747412-f55d9d0c-71c7-4956-87c7-72a07243822f.jpg)

**Comment by dgis** [comment]
Yes, it is possible with:
Layout: None
Rotation: Allow Rotation

**Comment by dgis** [comment]
I guess the issue is solved. I close the issue.
