### ISSUE TITLE
Emu48 v1.64 with the latest patch does not read certain KML files

### ISSUE THREAD

**Issue by acser123** [dgis/emu48android#19]
1. Unzip https://www.hpcalc.org/details/6569 into the Emu48 installation directory.
2. Start Emu48.
3. It will not show the HP50g option in the dropdown menu. 

This used to work.

**Comment by dgis** [comment]
Hi,
It does not work like that.
1. Open the menu.
2. Touch the "New..." menu item.
3. Touch "[Select a Custom KML script folder...]"
4. Select a the custom KML script folder "grokwikreal50g" where you have copied the KML scripts and THE ROM files named "ROMg+.49G" (Android 11 cannot use the folder Download).
5. And the calculator should now be opened.

"grokwikreal50g.zip" actually works on Emu48 for Android!
