### ISSUE TITLE
Auto-shutoff and the BEEP.48 patch file

### ISSUE THREAD

**Issue by ean365** [dgis/emu48android#22]
First of all -- **_THANK YOU_** -- for your work to make this available for Android.  (and thanks to Sebastian Carlier.) I use it all the time and it is appreciated.

One issue -- the calculator "shuts off" after about 10 minutes, and I need to "turn it back on".  This was a battery saving feature for the original physical calculator.  It is now somewhat annoying, and there is no need for this "feature" anymore since it is running in an emulator, and android will simply put it to sleep to save battery.

There is a ROM patch that is normally found in the BEEP.48 "patch" file that disables automatic shut-off:

BEEP.48
`01477:6300; disable 10 min auto off (internal, undocumented)`

However, the BEEP.48 file is not included in the `assets/calculators` directory of the .apk.
I notice that many of the KML files still include the line, `Patch BEEP.48`, even though the file does not exist.
Others, such as my favorite "_real48gx-lc.kml_", do not even include the line, `Patch BEEP.48`.

Would it be possible for you to do either one of the following to disable auto-shutoff?

1. Add the BEEP.48 file (with the above patch uncommented) to the `assets/calculators` directory, and also add the `Patch BEEP.48` line to all of the KML files.  (You could even rename the BEEP.48 file to NO-AUTO-OFF.48.)
2. Add an app setting called "disable auto-shutoff" that applies the patch.

**Comment by dgis** [comment]
Oh thank you, that sound as a great idea.
For the next release for sure.
