### ISSUE TITLE
MTH->BASE not working properly

### ISSUE THREAD

**Issue by smanders7** [dgis/emu48android#24]
It seems the BASE menu is not working properly. Any real number that I invoke R->B ends up as #1h or #0h. Any addition or conversion does not produce the correct binary number. 

A separate implementation of the emu48 emulator works great in this area.

**Comment by dgis** [comment]
I guess that you have
`RCWS`
->
`1: 1`
Try to set `64 STWS`, please.

**Comment by smanders7** [comment]
Wow...I love learning new things about this calculator after using it for 32 years.  I had no idea you could lower the bit width from 64.  Awesome!
