### ISSUE TITLE
White area at bottom

### ISSUE THREAD

**Issue by SammysHP** [dgis/emu48android#9]
Since 1.5 there is a white area at the bottom of the screen. Layout in preferences makes no difference, background is set to black and "do not use KML background color". Hiding the statusbar increases the area height.

![Screenshot_20190713-141506](https://user-images.githubusercontent.com/922874/61171525-ec434180-a578-11e9-8421-a15ac0b9d1ec.png)

**Comment by dgis** [comment]
This bug appears when both options "Hide status [or navigation] bar" and "Hide menu button" are checked!
